name: Build APK and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Install EAS
        run: npm install -g eas-cli

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Verify Expo Auth
        run: eas whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build APK
        run: eas build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Get build URL
        id: url
        run: |
          BUILD_URL=$(eas build:list --platform android --limit 1 --json | jq -r '.[0].artifacts.buildUrl')
          echo "url=$BUILD_URL" >> $GITHUB_OUTPUT
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download APK
        run: curl -L ${{ steps.url.outputs.url }} -o app.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: app.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}